// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;

namespace Azure.AI.OpenAI
{
    /// <summary> Model factory for models. </summary>
    public static partial class AzureOpenAIModelFactory
    {
        /// <summary> Initializes a new instance of Choice. </summary>
        /// <param name="text"> The generated text for a given completions prompt. </param>
        /// <param name="index"> The ordered index associated with this completions choice. </param>
        /// <param name="logProbabilityModel"> The log probabilities model for tokens associated with this completions choice. </param>
        /// <param name="finishReason"> Reason for finishing. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="text"/> is null. </exception>
        /// <returns> A new <see cref="OpenAI.Choice"/> instance for mocking. </returns>
        public static Choice Choice(string text = null, int index = default, CompletionsLogProbabilityModel logProbabilityModel = null, CompletionsFinishReason finishReason = default)
        {
            if (text == null)
            {
                throw new ArgumentNullException(nameof(text));
            }
            // Custom code: remove inappropriate null check of nullable CompletionsLogProbabilityModel

            return new Choice(text, index, logProbabilityModel, finishReason);
        }

        /// <summary> Initializes a new instance of ChatCompletions. </summary>
        /// <param name="id"> A unique identifier associated with this chat completions response. </param>
        /// <param name="created"> The first timestamp associated with generation activity for this completions response. </param>
        /// <param name="choices"> The collection of completions choices associated with this completions response. </param>
        /// <param name="usage"> Usage information for tokens processed and generated as part of this completions operation. </param>
        /// <returns> A new <see cref="OpenAI.ChatCompletions"/> instance for mocking. </returns>
        public static ChatCompletions ChatCompletions(string id = null, DateTimeOffset created = default(DateTimeOffset), IEnumerable<Choice> choices = null, CompletionsUsage usage = null)
        {
            choices ??= new List<Choice>();
            usage ??= AzureOpenAIModelFactory.CompletionsUsage();

            return new ChatCompletions(
                id: id ?? string.Empty,
                internalCreatedSecondsAfterUnixEpoch: created.ToUnixTimeSeconds(),
                choices: choices,
                usage: usage);
        }
    }
}
